---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: development
    app: weather-api
    tier: backend
  name: weather-api-ms
  namespace: development
spec:
  type: NodePort
  selector:
    app: weather-api
  ports:
  - name: api
    port: 8080
    targetPort: 8080

