apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-api-ms
  namespace: development
  labels:
    app: weather-api
    environment: development
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: weather-api-ms
  targetCPUUtilizationPercentage: 350
