version: "2"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: demo
#      MYSQL_USER: root
#      MYSQL_PASSWORD: admin@123

  redis:
    image: redis
    container_name: redis
    hostname: dockermachine
    ports:
      - 6379:6379

  weather-ms:
    image: weather-ms
    container_name: weather-ms
    hostname: dockermachine
    volumes:
      - /var/log/weather-ms:/var/log/weather-ms
    ports:
      - 8443:8443
      - 8080:8080
